apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    controller: message-dist
  name: message-dist
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: minio-port
      port: 8090
      protocol: TCP
      targetPort: 8090
  publishNotReadyAddresses: true
  selector:
    app: minio
    controller: message-dist
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: message-dist
  namespace: default
spec:
  podManagementPolicy: Parallel
  replicas: 4
  selector:
    matchLabels:
      app: minio
      controller: message-dist
  serviceName: message-dist
  template:
    metadata:
      labels:
        app: minio
        controller: message-dist
    spec:
      containers:
        - name: message
          command:
            - /message
            - http://message-dist-{0...3}.message-dist:8090/
          env:
            - name: MESSAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: dvaldivia/message:dist
#          imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8090
              name: minio-port
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data1
              name: data1
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: data1
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
