apiVersion: v1
kind: Service
metadata:
  labels:
    app: message
  name: message-lb
spec:
  ports:
    - name: http
      port: 8090
  selector:
    app: message
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: message
  name: message-1-svc
spec:
  ports:
    - name: http
      port: 8090
  selector:
    statefulset.kubernetes.io/pod-name: message-multi-svc-0
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: message
  name: message-2-svc
spec:
  ports:
    - name: http
      port: 8090
  selector:
    statefulset.kubernetes.io/pod-name: message-multi-svc-0
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: message
  name: message-3-svc
spec:
  ports:
    - name: http
      port: 8090
  selector:
    statefulset.kubernetes.io/pod-name: message-multi-svc-0
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: message
  name: message-0-svc
spec:
  ports:
    - name: http
      port: 8090
  selector:
    statefulset.kubernetes.io/pod-name: message-multi-svc-3
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: message-multi-svc
  namespace: default
spec:
  podManagementPolicy: Parallel
  replicas: 4
  selector:
    matchLabels:
      app: message
      controller: message-multi-svc
  serviceName: message-multi-svc
  template:
    metadata:
      labels:
        app: message
        controller: message-multi-svc
    spec:
      containers:
        - name: message
          command:
            - /message
            - http://message-{0...3}-svc:8090/
          env:
            - name: MESSAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: dvaldivia/message:dist
          #          imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /live
              port: 8090
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 8090
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8090
              name: minio-port
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data1
              name: data1
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: data1
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

